### ISSUE TITLE
Rails 4 Support?

### ISSUE THREAD

**Issue by bigtunacan** [timcharper/calendar_date_select#42]
Any chance we might get this?

**Comment by mikeastock** [comment]
@timcharper are you still looking for a maintainer?

**Comment by timcharper** [comment]
How did I not respond to this? I suck. Yes.

**Comment by mrj** [comment]
To get this to work in Rails 4.2.4, I had to [include the helpers](/timcharper/calendar_date_select/blob/master/lib/calendar_date_select.rb#L10) in `ActionView::Base` rather than `ActionView::Helpers`. I don't know whether this is the best solution.

**Comment by timcharper** [comment]
Yes. Wow, Jul 16th? I suck at responding :(

**Comment by mikeastock** [comment]
@timcharper my bad for not responding as well. Would are you thinking a new mainter would do? Take ownership. Respond to issues and keep the project up to date?

**Comment by timcharper** [comment]
Yes :) I don't use the project and pay very little attention to it, sadly. I'll hand over the reigns to you.

**Comment by timcharper** [comment]
So, wow I'm a HUGE idiot. @marcandre is still active and maintaining things. Do you want any help, @marcandre ? I'll just close this out.
