### ISSUE TITLE
@[] is not allowed as an instance variable name

### ISSUE THREAD

**Issue by NeelaveniT** [timcharper/calendar_date_select#47]
In My code : <%= calendar_date_select "project_effective_hour[from_date]",@project_effective_hour.from_date||Date.today,:popup=> 'force',:class => 'input-text'%>

Output : `@project_effective_hour[from_date]' is not allowed as an instance variable name

Kindly help me to resolve this issue.

**Comment by marcandre** [comment]
This library is not actively maintained. Only pull requests that are clearly well written are accepted.

**Comment by NeelaveniT** [comment]
I used it the gem by clone it.
In my code I changed as : <%= calendar_date_select "project_effective_hour[from_date]".instance_variable_get(@project_effective_hour).from_date||Date.today,:popup=> 'force',:class => 'input-text'%>

I used instance_variable_get because in the helper of the calendar_date_select they used instance_variable_get to value of the object.

My output : #<ProjectEffectiveHour id: 204, project_id: 170, effective_hours: #<BigDecimal:7fdcb5b07ef0,'0.4E1',9(18)>, from_date: "2016-02-06", to_date: "2016-05-31", created_at: "2016-02-16 18:59:11", updated_at: "2016-09-07 15:09:24", effective_hrs_for_days: 1> is not a symbol nor a string

I able to retrieve the output of the query but it shows as not as symbol nor a string

kindly help me to resolve it.

**Comment by NeelaveniT** [comment]
The previous code in rails Rails 2.3.8 ,they use calendar_date_select_tag for calendar.
But I migrate the code to rails 4.2.7 ,so I wish to use calendar_date_select.
Kindly help me,how to use it and how to include in view.
