### ISSUE TITLE
How to use calendar_date_select gem on rails 4

### ISSUE THREAD

**Issue by NeelaveniT** [timcharper/calendar_date_select#48]
Kindly help me,how to use calendar_date_select gem in rails 4 application.

**Comment by marcandre** [comment]
This library is not actively maintained. Only pull requests that are clearly well written are accepted.

**Comment by NeelaveniT** [comment]
I used it the gem by clone it.
In my code I changed as : <%= calendar_date_select "project_effective_hour[from_date]".instance_variable_get(@project_effective_hour).from_date||Date.today,:popup=> 'force',:class => 'input-text'%>

I used instance_variable_get because in the helper of the calendar_date_select they used instance_variable_get to value of the object.

My output : #, from_date: "2016-02-06", to_date: "2016-05-31", created_at: "2016-02-16 18:59:11", updated_at: "2016-09-07 15:09:24", effective_hrs_for_days: 1> is not a symbol nor a string

I able to retrieve the output of the query but it shows as not as symbol nor a string

kindly help me to resolve it.

**Comment by NeelaveniT** [comment]
The previous code in rails Rails 2.3.8 ,they use calendar_date_select_tag for calendar.
But I migrate the code to rails 4.2.7 ,so I wish to use calendar_date_select.
Kindly help me,how to use it.

**Comment by mltsy** [comment]
I was able to get it working recently with a couple modifications to the gem. If you wanted to fork it and post the errors you're getting here, you could probably make your own fork work.

**However** ... I just replaced it with jQuery datepicker - much nicer option at this point! :)
See [jquery-ui-rails gem](https://github.com/joliss/jquery-ui-rails#require-specific-modules)
