### ISSUE TITLE
undefined method `options_for_javascript' for #<#<Class:xxx> (ActionView::Template::Error)

### ISSUE THREAD

**Issue by zedtux** [timcharper/calendar_date_select#49]
This gem with Rails 4.2 is failing with the following error:

```
undefined method `options_for_javascript' for #<#<Class:0x007f0c22c01540>:0x007f0c22c04740> (ActionView::Template::Error)
```

I could be wrong, but it seems this method has been removed in Rails 4 (http://apidock.com/rails/ActionView/Helpers/UrlHelper/options_for_javascript).

**Comment by NeelaveniT** [comment]
same issue for me also

**Comment by marcandre** [comment]
I updated the Readme to make it clear that there is no interested maintainer for this library. I'll merge PRs that are obviously correct.

**Comment by zedtux** [comment]
Repo no more maintained as said by @marcandre ... closing the issue.
